Repository scaleway/scaleway-form, pull requests merged in 2022-10, with the labels that each got.

#520 fix: webpack build stuck
  .storybook/.babelrc
  .storybook/babel.config.json
  .storybook/main.ts
  package.json
  pnpm-lock.yaml
  src/components/DateField/__tests__/index.tsx
Labels: bug

#522 feat: add unit prop
  src/components/TextBoxField/index.tsx
Labels: enhancement

#511 fix: update scaleway ui v0.198.0
  package.json
  pnpm-lock.yaml
  src/components/CheckboxField/__tests__/__snapshots__/index.spec.tsx.snap
  src/components/DateField/__tests__/__snapshots__/index.tsx.snap
  src/components/DateField/index.tsx
  src/components/RadioField/__tests__/__snapshots__/index.spec.tsx.snap
  src/components/SelectableCardField/__tests__/__snapshots__/index.spec.tsx.snap
  src/components/SubmitErrorAlert/__tests__/__snapshots__/index.spec.tsx.snap
Labels: dependencies

#528 ci: use static-web-server
  Dockerfile
Labels: enhancement

#510 feat: enable dynamic validation
  src/components/CheckboxField/index.tsx
  src/components/DateField/index.tsx
  src/components/RadioField/index.tsx
  src/components/RichSelectField/index.tsx
  src/components/SelectNumberField/index.tsx
  src/components/SelectableCardField/index.tsx
  src/components/TagsField/index.tsx
  src/components/TextBoxField/__stories__/index.stories.tsx
  src/components/TextBoxField/index.tsx
  src/components/TimeField/index.tsx
  src/components/ToggleField/index.tsx
  src/hooks/__tests__/useFormField.spec.tsx
  src/hooks/index.ts
  src/hooks/useFormField.ts
  src/hooks/useValidation.ts
Labels: enhancement

#526 fix: do not display error on checkbox on form load
  src/providers/ErrorContext/index.tsx
Labels: bug

#554 fix: validation when field is not required
  src/validators/max.ts
  src/validators/maxDate.ts
  src/validators/maxLength.ts
  src/validators/min.ts
  src/validators/minDate.ts
  src/validators/minLength.ts
  src/validators/regex.ts
Labels: bug

#555 fix: infinite rendering when passing form render props
  src/hooks/useFormField.ts
Labels: bug
