Repository scaleway/scaleway-form, pull requests merged in 2022-08, with the labels that each got.

#446 fix: add export of selectablecardfield
  src/index.ts
Labels: bug

#442 fix(richSelect): error when untouched
  src/components/RichSelectField/index.tsx
Labels: bug

#449 feat: react 18
  package.json
  pnpm-lock.yaml
  src/components/DateField/__tests__/index.tsx
  src/helpers/jestHelpers.tsx
  src/hooks/__tests__/useValidation.spec.ts
  src/providers/ErrorContext/__tests__/index.spec.tsx
Labels: dependencies

#457 fix(SelectableCard): children type
  src/components/SelectableCardField/index.tsx
Labels: bug

#464 fix: required={false} should work
  src/validators/__tests__/required.spec.ts
  src/validators/required.ts
Labels: bug

#465 refactor(Toggle): switch to toggle
  package.json
  pnpm-lock.yaml
  src/components/CheckboxField/__tests__/__snapshots__/index.spec.tsx.snap
  src/components/CheckboxField/index.tsx
  src/components/DateField/__tests__/__snapshots__/index.tsx.snap
  src/components/RadioBorderedBoxField/__tests__/__snapshots__/index.spec.tsx.snap
  src/components/RadioField/__tests__/__snapshots__/index.spec.tsx.snap
  src/components/RichSelectField/__tests__/__snapshots__/index.spec.tsx.snap
  src/components/SelectableCardField/__tests__/__snapshots__/index.spec.tsx.snap
  src/components/Submit/__tests__/__snapshots__/index.spec.tsx.snap
  src/components/SubmitErrorAlert/__tests__/__snapshots__/index.spec.tsx.snap
  src/components/SwitchField/__tests__/__snapshots__/index.spec.tsx.snap
  src/components/SwitchField/__tests__/index.spec.tsx
  src/components/SwitchField/index.tsx
  src/components/TagsField/__tests__/__snapshots__/index.spec.tsx.snap
  src/components/TagsField/__tests__/index.spec.tsx
  src/components/TextBoxField/__tests__/__snapshots__/index.spec.tsx.snap
  src/components/TimeField/__tests__/__snapshots__/index.spec.tsx.snap
  src/components/ToggleField/__stories__/index.stories.tsx
  src/components/ToggleField/__tests__/__snapshots__/index.spec.tsx.snap
  src/components/ToggleField/__tests__/index.spec.tsx
  src/components/ToggleField/index.tsx
  src/index.ts
Labels: enhancement

#380 fix: skipping initial button state
  src/components/Submit/index.tsx
Labels: enhancement
